In [18]:
import pandas as pd 
import numpy as np

In [30]:
df=pd.read_csv('data (1).csv')

In [31]:
df.head()

,Unnamed: 0,Id,groupId,matchId,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,killPoints,kills,killStreaks,longestKill,matchDuration,matchType,maxPlace,numGroups,rankPoints,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc
0,2093518,a3e3cea9f2e314,c9f6eaa81245b5,a3d8693390584c,0,0,25.93,0,0,0,84,1437,0,0,0.000,1403,squad-fpp,31,29,-1,0,0.0,0,0.0,0,0,151.30,1,1525,0.0667
1,3701672,43e4be7ad72cc7,521836de101ee8,b65de9055327e0,0,0,36.71,0,0,0,57,1225,0,0,0.000,1971,squad-fpp,30,30,-1,0,0.0,0,0.0,0,0,1918.00,7,1516,0.5862
2,2059784,9a68690e31fdff,4a72ffa2cebd90,d6aad3f9830e60,0,1,47.73,0,0,0,50,0,0,0,0.000,1741,solo-fpp,96,89,1516,0,4088.0,0,0.0,0,0,820.00,7,0,0.8105
3,1302036,b147e1bd448fc4,9a8991656b3fea,d931c0932d8aca,0,0,0.00,0,0,0,56,1286,0,0,0.000,1738,squad-fpp,28,27,-1,1,0.0,0,0.0,0,0,38.81,0,1515,0.5556
4,297180,d818b4edd59612,eece87c8b846b3,ec2b5ed94baae3,0,2,100.00,0,0,3,31,0,1,1,7.737,2193,solo,99,95,1482,0,918.4,0,0.0,0,0,1721.00,5,0,0.6429

In [33]:
df.drop(columns = ['matchId', 'groupId', 'Id', 'Unnamed: 0'], inplace = True)  #removing unnecessary rows

In [34]:
df.head()

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,killPoints,kills,killStreaks,longestKill,matchDuration,matchType,maxPlace,numGroups,rankPoints,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc
0,0,0,25.93,0,0,0,84,1437,0,0,0.000,1403,squad-fpp,31,29,-1,0,0.0,0,0.0,0,0,151.30,1,1525,0.0667
1,0,0,36.71,0,0,0,57,1225,0,0,0.000,1971,squad-fpp,30,30,-1,0,0.0,0,0.0,0,0,1918.00,7,1516,0.5862
2,0,1,47.73,0,0,0,50,0,0,0,0.000,1741,solo-fpp,96,89,1516,0,4088.0,0,0.0,0,0,820.00,7,0,0.8105
3,0,0,0.00,0,0,0,56,1286,0,0,0.000,1738,squad-fpp,28,27,-1,1,0.0,0,0.0,0,0,38.81,0,1515,0.5556
4,0,2,100.00,0,0,3,31,0,1,1,7.737,2193,solo,99,95,1482,0,918.4,0,0.0,0,0,1721.00,5,0,0.6429

In [36]:
df.describe()

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,killPoints,kills,killStreaks,longestKill,matchDuration,maxPlace,numGroups,rankPoints,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc
count,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111742e+06,1.111741e+06
mean,2.336738e-01,1.106655e+00,1.307364e+02,6.573612e-01,2.266488e-01,1.370348e+00,4.759562e+01,5.044301e+02,9.255097e-01,5.448503e-01,2.299814e+01,1.579348e+03,4.450584e+01,4.300693e+01,8.927902e+02,1.641784e-01,6.042142e+02,3.551184e-03,4.545068e+00,2.401097e-02,7.833652e-03,1.153282e+03,3.659685e+00,6.057065e+02,4.727868e-01
std,5.894028e-01,1.716050e+00,1.711755e+02,1.146023e+00,6.033356e-01,2.683819e+00,2.747025e+01,6.274006e+02,1.562216e+00,7.129032e-01,5.106977e+01,2.589348e+02,2.381989e+01,2.327841e+01,7.366443e+02,4.704189e-01,1.495949e+03,7.385452e-02,3.061857e+01,1.678909e-01,9.194621e-02,1.182788e+03,2.461805e+00,7.395140e+02,3.073771e-01
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.400000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.367000e+03,2.800000e+01,2.700000e+01,-1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.552000e+02,2.000000e+00,0.000000e+00,2.000000e-01
50%,0.000000e+00,0.000000e+00,8.411000e+01,0.000000e+00,0.000000e+00,0.000000e+00,4.700000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.438000e+03,3.000000e+01,3.000000e+01,1.444000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.841000e+02,3.000000e+00,0.000000e+00,4.583000e-01
75%,0.000000e+00,2.000000e+00,1.859000e+02,1.000000e+00,0.000000e+00,2.000000e+00,7.100000e+01,1.171000e+03,1.000000e+00,1.000000e+00,2.133000e+01,1.851000e+03,4.900000e+01,4.700000e+01,1.500000e+03,0.000000e+00,7.927500e-02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.975000e+03,5.000000e+00,1.495000e+03,7.407000e-01
max,1.700000e+01,2.400000e+01,5.990000e+03,3.500000e+01,6.400000e+01,7.300000e+01,1.000000e+02,2.170000e+03,7.200000e+01,2.000000e+01,1.040000e+03,2.237000e+03,1.000000e+02,1.000000e+02,5.910000e+03,2.300000e+01,3.540000e+04,1.400000e+01,2.668000e+03,1.000000e+01,5.000000e+00,1.396000e+04,1.770000e+02,2.002000e+03,1.000000e+00

In [38]:
df.isna().sum()   #to check total nan values

assists            0
boosts             0
damageDealt        0
DBNOs              0
headshotKills      0
heals              0
killPlace          0
killPoints         0
kills              0
killStreaks        0
longestKill        0
matchDuration      0
matchType          0
maxPlace           0
numGroups          0
rankPoints         0
revives            0
rideDistance       0
roadKills          0
swimDistance       0
teamKills          0
vehicleDestroys    0
walkDistance       0
weaponsAcquired    0
winPoints          0
winPlacePerc       1
dtype: int64

In [ ]:
#df.dropna(axis = 1, inplace = True)

In [40]:
df.kills.unique()

array([ 0,  1,  4,  3,  2,  5,  6,  7,  8, 13, 10, 12,  9, 11, 26, 16, 15,
       23, 18, 17, 19, 14, 20, 21, 22, 24, 34, 38, 33, 29, 30, 36, 53, 40,
       42, 32, 39, 50, 37, 27, 47, 25, 56, 72, 35, 28, 55, 41, 44],
      dtype=int64)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1111742 entries, 0 to 1111741
Data columns (total 26 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   assists          1111742 non-null  int64
 1   boosts           1111742 non-null  int64
 2   damageDealt      1111742 non-null  float64
 3   DBNOs            1111742 non-null  int64
 4   headshotKills    1111742 non-null  int64
 5   heals            1111742 non-null  int64
 6   killPlace        1111742 non-null  int64
 7   killPoints       1111742 non-null  int64
 8   kills            1111742 non-null  int64
 9   killStreaks      1111742 non-null  int64
 10  longestKill      1111742 non-null  float64
 11  matchDuration    1111742 non-null  int64
 12  matchType        1111742 non-null  object
 13  maxPlace         1111742 non-null  int64
 14  numGroups        1111742 non-null  int64
 15  rankPoints       1111742 non-null  int64
 16  revives          1111742 non-null  int64
 17  rideDistance     1111742 non-null  float64
 18  roadKills        1111742 non-null  int64
 19  swimDistance     1111742 non-null  float64
 20  teamKills        1111742 non-null  int64
 21  vehicleDestroys  1111742 non-null  int64
 22  walkDistance     1111742 non-null  float64
 23  weaponsAcquired  1111742 non-null  int64
 24  winPoints        1111742 non-null  int64
 25  winPlacePerc     1111741 non-null  float64
dtypes: float64(6), int64(19), object(1)
memory usage: 220.5+ MB

In [44]:
df.matchType.unique()   #checking total unique values

array(['squad-fpp', 'solo-fpp', 'solo', 'duo', 'duo-fpp', 'squad',
       'normal-squad-fpp', 'normal-duo-fpp', 'normal-solo-fpp',
       'crashfpp', 'crashtpp', 'normal-squad', 'flaretpp', 'flarefpp',
       'normal-duo', 'normal-solo'], dtype=object)

In [45]:
matchtype = pd.get_dummies(df['matchType'],drop_first=True)   #from categorical to numerical
matchtype

,crashtpp,duo,duo-fpp,flarefpp,flaretpp,normal-duo,normal-duo-fpp,normal-solo,normal-solo-fpp,normal-squad,normal-squad-fpp,solo,solo-fpp,squad,squad-fpp
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1111737,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1111738,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
1111739,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1111740,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1111741,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [46]:
df = pd.concat([df,matchtype],axis=1)     #concatenating into main dataset
df.head() # checking the dataset after transformation

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,killPoints,kills,killStreaks,longestKill,matchDuration,matchType,maxPlace,numGroups,rankPoints,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc,crashtpp,duo,duo-fpp,flarefpp,flaretpp,normal-duo,normal-duo-fpp,normal-solo,normal-solo-fpp,normal-squad,normal-squad-fpp,solo,solo-fpp,squad,squad-fpp
0,0,0,25.93,0,0,0,84,1437,0,0,0.000,1403,squad-fpp,31,29,-1,0,0.0,0,0.0,0,0,151.30,1,1525,0.0667,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,0,0,36.71,0,0,0,57,1225,0,0,0.000,1971,squad-fpp,30,30,-1,0,0.0,0,0.0,0,0,1918.00,7,1516,0.5862,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0,1,47.73,0,0,0,50,0,0,0,0.000,1741,solo-fpp,96,89,1516,0,4088.0,0,0.0,0,0,820.00,7,0,0.8105,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,0,0,0.00,0,0,0,56,1286,0,0,0.000,1738,squad-fpp,28,27,-1,1,0.0,0,0.0,0,0,38.81,0,1515,0.5556,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,0,2,100.00,0,0,3,31,0,1,1,7.737,2193,solo,99,95,1482,0,918.4,0,0.0,0,0,1721.00,5,0,0.6429,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1111742 entries, 0 to 1111741
Data columns (total 41 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   assists           1111742 non-null  int64
 1   boosts            1111742 non-null  int64
 2   damageDealt       1111742 non-null  float64
 3   DBNOs             1111742 non-null  int64
 4   headshotKills     1111742 non-null  int64
 5   heals             1111742 non-null  int64
 6   killPlace         1111742 non-null  int64
 7   killPoints        1111742 non-null  int64
 8   kills             1111742 non-null  int64
 9   killStreaks       1111742 non-null  int64
 10  longestKill       1111742 non-null  float64
 11  matchDuration     1111742 non-null  int64
 12  matchType         1111742 non-null  object
 13  maxPlace          1111742 non-null  int64
 14  numGroups         1111742 non-null  int64
 15  rankPoints        1111742 non-null  int64
 16  revives           1111742 non-null  int64
 17  rideDistance      1111742 non-null  float64
 18  roadKills         1111742 non-null  int64
 19  swimDistance      1111742 non-null  float64
 20  teamKills         1111742 non-null  int64
 21  vehicleDestroys   1111742 non-null  int64
 22  walkDistance      1111742 non-null  float64
 23  weaponsAcquired   1111742 non-null  int64
 24  winPoints         1111742 non-null  int64
 25  winPlacePerc      1111741 non-null  float64
 26  crashtpp          1111742 non-null  uint8
 27  duo               1111742 non-null  uint8
 28  duo-fpp           1111742 non-null  uint8
 29  flarefpp          1111742 non-null  uint8
 30  flaretpp          1111742 non-null  uint8
 31  normal-duo        1111742 non-null  uint8
 32  normal-duo-fpp    1111742 non-null  uint8
 33  normal-solo       1111742 non-null  uint8
 34  normal-solo-fpp   1111742 non-null  uint8
 35  normal-squad      1111742 non-null  uint8
 36  normal-squad-fpp  1111742 non-null  uint8
 37  solo              1111742 non-null  uint8
 38  solo-fpp          1111742 non-null  uint8
 39  squad             1111742 non-null  uint8
 40  squad-fpp         1111742 non-null  uint8
dtypes: float64(6), int64(19), object(1), uint8(15)
memory usage: 236.4+ MB

In [48]:
df.drop(['matchType'], axis = 1, inplace = True)   #removing matchtype column after converting into numerical rows

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1111742 entries, 0 to 1111741
Data columns (total 40 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   assists           1111742 non-null  int64
 1   boosts            1111742 non-null  int64
 2   damageDealt       1111742 non-null  float64
 3   DBNOs             1111742 non-null  int64
 4   headshotKills     1111742 non-null  int64
 5   heals             1111742 non-null  int64
 6   killPlace         1111742 non-null  int64
 7   killPoints        1111742 non-null  int64
 8   kills             1111742 non-null  int64
 9   killStreaks       1111742 non-null  int64
 10  longestKill       1111742 non-null  float64
 11  matchDuration     1111742 non-null  int64
 12  maxPlace          1111742 non-null  int64
 13  numGroups         1111742 non-null  int64
 14  rankPoints        1111742 non-null  int64
 15  revives           1111742 non-null  int64
 16  rideDistance      1111742 non-null  float64
 17  roadKills         1111742 non-null  int64
 18  swimDistance      1111742 non-null  float64
 19  teamKills         1111742 non-null  int64
 20  vehicleDestroys   1111742 non-null  int64
 21  walkDistance      1111742 non-null  float64
 22  weaponsAcquired   1111742 non-null  int64
 23  winPoints         1111742 non-null  int64
 24  winPlacePerc      1111741 non-null  float64
 25  crashtpp          1111742 non-null  uint8
 26  duo               1111742 non-null  uint8
 27  duo-fpp           1111742 non-null  uint8
 28  flarefpp          1111742 non-null  uint8
 29  flaretpp          1111742 non-null  uint8
 30  normal-duo        1111742 non-null  uint8
 31  normal-duo-fpp    1111742 non-null  uint8
 32  normal-solo       1111742 non-null  uint8
 33  normal-solo-fpp   1111742 non-null  uint8
 34  normal-squad      1111742 non-null  uint8
 35  normal-squad-fpp  1111742 non-null  uint8
 36  solo              1111742 non-null  uint8
 37  solo-fpp          1111742 non-null  uint8
 38  squad             1111742 non-null  uint8
 39  squad-fpp         1111742 non-null  uint8
dtypes: float64(6), int64(19), uint8(15)
memory usage: 228.0 MB

In [51]:
lst = ['duo', 'duo-fpp','flaretpp','normal-duo-fpp','normal-solo-fpp','normal-squad','normal-squad-fpp','solo',
'solo-fpp',        
'squad',             
'squad-fpp']

In [54]:
for i in lst:                     #changing type from uint8 to int64
    df[i] = df[i].astype('int64')

In [55]:
df.head()

,assists,boosts,damageDealt,DBNOs,headshotKills,heals,killPlace,killPoints,kills,killStreaks,longestKill,matchDuration,maxPlace,numGroups,rankPoints,revives,rideDistance,roadKills,swimDistance,teamKills,vehicleDestroys,walkDistance,weaponsAcquired,winPoints,winPlacePerc,crashtpp,duo,duo-fpp,flarefpp,flaretpp,normal-duo,normal-duo-fpp,normal-solo,normal-solo-fpp,normal-squad,normal-squad-fpp,solo,solo-fpp,squad,squad-fpp
0,0,0,25.93,0,0,0,84,1437,0,0,0.000,1403,31,29,-1,0,0.0,0,0.0,0,0,151.30,1,1525,0.0667,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
1,0,0,36.71,0,0,0,57,1225,0,0,0.000,1971,30,30,-1,0,0.0,0,0.0,0,0,1918.00,7,1516,0.5862,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0,1,47.73,0,0,0,50,0,0,0,0.000,1741,96,89,1516,0,4088.0,0,0.0,0,0,820.00,7,0,0.8105,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,0,0,0.00,0,0,0,56,1286,0,0,0.000,1738,28,27,-1,1,0.0,0,0.0,0,0,38.81,0,1515,0.5556,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
4,0,2,100.00,0,0,3,31,0,1,1,7.737,2193,99,95,1482,0,918.4,0,0.0,0,0,1721.00,5,0,0.6429,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0

In [56]:
df.killStreaks.unique()

array([ 0,  1,  2,  4,  3,  5,  9, 16,  7,  6, 13,  8, 12, 10, 20],
      dtype=int64)

In [57]:
df.drop(df.index[df['kills'] == 26], inplace = True)     #since 26 had only 1 value in dataset so removing it now to enhance model performance

In [58]:
df.drop(df.index[df['kills'] == 16], inplace = True)

In [59]:
import matplotlib.pyplot as plt
import seaborn as sns

In [60]:
#sns.barplot('kills','killStreaks',hue='damageDealt',data=df)     #visualization was taking long time to execute so didnt do

In [61]:
'''print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)'''

df.columns

Index(['assists', 'boosts', 'damageDealt', 'DBNOs', 'headshotKills', 'heals',
       'killPlace', 'killPoints', 'kills', 'killStreaks', 'longestKill',
       'matchDuration', 'maxPlace', 'numGroups', 'rankPoints', 'revives',
       'rideDistance', 'roadKills', 'swimDistance', 'teamKills',
       'vehicleDestroys', 'walkDistance', 'weaponsAcquired', 'winPoints',
       'winPlacePerc', 'crashtpp', 'duo', 'duo-fpp', 'flarefpp', 'flaretpp',
       'normal-duo', 'normal-duo-fpp', 'normal-solo', 'normal-solo-fpp',
       'normal-squad', 'normal-squad-fpp', 'solo', 'solo-fpp', 'squad',
       'squad-fpp'],
      dtype='object')

In [ ]:
# scaling the data
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X =  pd.DataFrame(sc_X.fit_transform(df.drop(["kills"],axis = 1),),
        columns=['assists', 'boosts', 'damageDealt', 'DBNOs', 'headshotKills', 'heals',
       'killPlace', 'killPoints', 'killStreaks', 'longestKill',
       'matchDuration', 'maxPlace', 'numGroups', 'rankPoints', 'revives',
       'rideDistance', 'roadKills', 'swimDistance', 'teamKills',
       'vehicleDestroys', 'walkDistance', 'weaponsAcquired', 'winPoints',
       'winPlacePerc', 'crashtpp', 'duo', 'duo-fpp', 'flaretpp',
       'normal-duo-fpp', 'normal-solo-fpp', 'normal-squad', 'normal-squad-fpp',
       'solo', 'solo-fpp', 'squad', 'squad-fpp'])

In [63]:
y = df.kills  # assigning the label column

In [ ]:
#splitting the data into training and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.4,random_state=42)

In [ ]:
from sklearn.decomposition import PCA
import numpy as np
pca = PCA()
principalComponents = pca.fit_transform(X)
plt.figure()
plt.plot(np.cumsum(pca.explained_variance_ratio_))
plt.xlabel('Number of Components')
plt.ylabel('Variance (%)') #for each component
plt.title('Explained Variance')
plt.show()

In [ ]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

In [ ]:
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, roc_curve, roc_auc_score

In [ ]:
grid_param = {
    'criterion': ['gini', 'entropy'],
    'max_depth' : range(2,32,1),
    'min_samples_leaf' : range(1,10,1),
    'min_samples_split': range(2,10,1),
    'splitter' : ['best', 'random']

In [ ]:
grid_search = GridSearchCV(estimator=clf,
                     param_grid=grid_param,
                    cv = 2,
                    n_jobs =-1)

In [ ]:
best_parameters = grid_search.best_params_
print(best_parameters)

In [ ]:
#for more accuracy
grid_param = {
    'criterion': ['gini', 'entropy'],
    'max_depth' : range(2,32,1),
    'min_samples_leaf' : range(1,10,1),
    'min_samples_split': range(2,10,1),
    'splitter' : ['best', 'random']

In [ ]:
grid_search = GridSearchCV(estimator=clf,
                     param_grid=grid_param,
                    cv = 2,
                    n_jobs =-1)

In [ ]:
clf = DecisionTreeClassifier(criterion = 'entropy', max_depth =13, min_samples_leaf= 9, min_samples_split= 5, splitter ='random')
clf.fit(X_train,y_train)

In [ ]:
clf.score(X_test,y_test)